
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Osoba [
<!ELEMENT Osoba (punoIme, datumRodjenja, Adresa, Email+)>
<!ELEMENT punoIme (Ime, srednjeIme?, Prezime+)>
<!ELEMENT datumRodjenja (Dan, Mesec, Godina)>
<!ELEMENT Adresa (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT srednjeIme (#PCDATA)>
<!ELEMENT Prezime (#PCDATA)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ATTLIST Adresa odrediste (privremena | stalna) "privremena">
<!ATTLIST Email vrsta (sluzbeni | privatni) #IMPLIED>
]>

<Osoba>
  <punoIme>
    <Ime>Nikola</Ime>
    <srednjeIme></srednjeIme>
    <Prezime>Stosevski</Prezime>
  </punoIme>
  <datumRodjenja>
    <Dan>19</Dan>
    <Mesec>12</Mesec>
    <Godina>1998</Godina>
  </datumRodjenja>
  <Adresa odrediste="stalna">Beograd</Adresa>
  <Email  vrsta="sluzbeni">example@exp.com</Email>
</Osoba>